export const ZH_CN_COPY = {
  settings: '设置',
  closeSettings: '关闭设置',
  close: '关闭',
  language: '语言',
  languageSystem: '系统默认',
  languageChinese: '中文',
  languageEnglish: 'English',
  appDescription:
    '基于浏览器的 Android 自动化控制台，支持 WebADB 和 OpenAI 兼容视觉模型。',
  githubRepository: 'GitHub 仓库',
  repositoryStats: '仓库统计',
  stars: '星标',
  forks: '复刻',
  openIssues: '开放问题',
  githubStatsError: '暂时无法加载 GitHub 统计。',
  theme: '主题',
  themeSystem: '系统',
  themeLight: '浅色',
  themeDark: '深色',
  webUsbReady: '可用',
  webUsbMissing: '不可用',
  model: '模型',
  noModel: '未设置模型',
  modelSettings: '模型设置',
  baseUrl: 'Base URL',
  apiKey: 'API Key',
  streamModelResponses: '流式模型响应',
  device: '设备',
  noDevice: '无设备',
  deviceDetails: '设备详情',
  serial: '序列号',
  currentApp: '当前应用',
  package: '包名',
  activity: 'Activity',
  keyboard: '键盘',
  usbDebuggingRequired: '需要 USB 调试',
  connect: '连接',
  adbConnectionHelpLabel: 'ADB 连接帮助',
  adbConnectionHelpText: '如果连接不上，请在终端输入 adb kill-server，然后重新连接设备。',
  disconnect: '断开',
  capture: '截图',
  installAdbKeyboard: '安装 ADB 键盘',
  adbKeyboardInstalled: 'ADB 键盘已安装',
  enableAdbKeyboard: '启用 ADB 键盘',
  runDoctor: '运行 Doctor',
  doctorChecks: 'Doctor 检查',
  doctorSummary: 'Doctor 摘要',
  installedApps: '已安装应用',
  appSearch: '搜索应用',
  launchApp: '启动',
  launchInstalledApp: (name: string) => `启动 ${name}`,
  noInstalledApps: '没有找到应用',
  deviceOptions: '设备选项',
  directCommands: '直接设备命令',
  directCommand: '直接设备命令',
  tapX: '点击 X',
  tapY: '点击 Y',
  runTap: '执行点击',
  swipeFromX: '起点 X',
  swipeFromY: '起点 Y',
  swipeToX: '终点 X',
  swipeToY: '终点 Y',
  runSwipe: '执行滑动',
  directText: '文本',
  runType: '执行输入',
  runBack: '返回',
  runHome: '主页',
  runEnter: '回车',
  useAdbKeyboard: '文本输入使用 ADB 键盘',
  confirmSensitiveActions: '确认敏感动作',
  sensitiveActionTitle: '请求执行敏感动作',
  sensitiveActionPrompt: '是否执行？',
  actionSettle: '动作等待 (ms)',
  doubleTapInterval: '双击间隔 (ms)',
  keyboardStep: '键盘步进 (ms)',
  supportedActions: '支持的动作',
  capabilities: [
    '启动',
    '点击',
    '输入',
    '滑动',
    '返回',
    '主页',
    '长按',
    '双击',
    '等待',
    '接管',
  ],
  androidScreenshot: 'Android 截图',
  expandedAndroidScreenshot: '展开的 Android 截图',
  screenshotInteractionLayer: '截图交互层',
  runGeneratedAction: '执行生成的动作',
  clearGeneratedAction: '清除生成的动作',
  openScreenshotFor: (title: string) => `打开截图：${title}`,
  screenshotDialogFor: (title: string) => `${title}预览`,
  closeScreenshotPreview: '关闭截图预览',
  screenshotZoomControls: '截图缩放控件',
  zoomInScreenshot: '放大截图',
  zoomOutScreenshot: '缩小截图',
  resetScreenshotZoom: '重置截图缩放',
  showPhoneFullscreen: '全屏显示手机',
  exitPhoneFullscreen: '退出手机全屏',
  fullscreenPhonePreview: '全屏手机预览',
  noScreenshot: '暂无截图',
  chat: '聊天',
  conversation: '对话',
  noMessages: '暂无消息',
  chatMessage: '聊天消息',
  chatPlaceholder: '发送后续指令...',
  taskTemplate: '任务模板',
  chooseTaskTemplate: '选择模板...',
  send: '发送',
  newChat: '新聊天',
  typeMessageFirst: '请先输入消息。',
  agentRun: '智能体运行',
  executionMode: '执行模式',
  manualMode: '单步计划',
  autoMode: '自动运行',
  planNextStep: '规划下一步',
  runAgent: '运行任务',
  running: '运行中...',
  runUnavailable: '请先连接设备、配置模型，并发送或选择任务。',
  waitForCurrentRun: '请等待当前运行结束。',
  maxSteps: '最大步数',
  autoExecute: '自动执行',
  runOptions: '运行选项',
  plan: '计划',
  run: '运行',
  stop: '停止',
  reset: '重置',
  export: '导出',
  pendingAction: '待处理动作',
  step: '步骤',
  none: '无',
  acknowledge: '确认',
  finish: '完成',
  execute: '执行',
  user: '用户',
  assistant: '助手',
  observation: '观察',
  runLog: '运行日志',
  clear: '清空',
  noEvents: '暂无事件',
} as const
