export const EN_US_COPY = {
  settings: 'Settings',
  closeSettings: 'Close settings',
  close: 'Close',
  language: 'Language',
  languageSystem: 'System default',
  languageChinese: '中文',
  languageEnglish: 'English',
  appDescription:
    'Browser-based Android automation console for WebADB and OpenAI-compatible vision models.',
  githubRepository: 'GitHub repository',
  repositoryStats: 'Repository stats',
  stars: 'Stars',
  forks: 'Forks',
  openIssues: 'Open issues',
  githubStatsError: 'Could not load GitHub stats right now.',
  theme: 'Theme',
  themeSystem: 'System',
  themeLight: 'Light',
  themeDark: 'Dark',
  webUsbReady: 'ready',
  webUsbMissing: 'missing',
  model: 'Model',
  noModel: 'No model',
  modelSettings: 'Model settings',
  baseUrl: 'Base URL',
  apiKey: 'API Key',
  streamModelResponses: 'Stream model responses',
  device: 'Device',
  noDevice: 'No device',
  deviceDetails: 'Device details',
  serial: 'Serial',
  currentApp: 'Current app',
  package: 'Package',
  activity: 'Activity',
  keyboard: 'Keyboard',
  usbDebuggingRequired: 'USB debugging required',
  connect: 'Connect',
  adbConnectionHelpLabel: 'ADB connection help',
  adbConnectionHelpText:
    'If the connection fails, run adb kill-server in your terminal, then reconnect the device.',
  disconnect: 'Disconnect',
  capture: 'Capture',
  installAdbKeyboard: 'Install ADB Keyboard',
  adbKeyboardInstalled: 'ADB Keyboard installed',
  enableAdbKeyboard: 'Enable ADB Keyboard',
  runDoctor: 'Run Doctor',
  doctorChecks: 'Doctor checks',
  doctorSummary: 'Doctor summary',
  installedApps: 'Installed apps',
  appSearch: 'App search',
  launchApp: 'Launch',
  launchInstalledApp: (name: string) => `Launch ${name}`,
  noInstalledApps: 'No installed apps found',
  deviceOptions: 'Device options',
  directCommands: 'Direct commands',
  directCommand: 'Direct command',
  tapX: 'Tap X',
  tapY: 'Tap Y',
  runTap: 'Run Tap',
  swipeFromX: 'From X',
  swipeFromY: 'From Y',
  swipeToX: 'To X',
  swipeToY: 'To Y',
  runSwipe: 'Run Swipe',
  directText: 'Text',
  runType: 'Run Type',
  runBack: 'Back',
  runHome: 'Home',
  runEnter: 'Enter',
  useAdbKeyboard: 'Use ADB Keyboard for text',
  confirmSensitiveActions: 'Confirm sensitive actions',
  sensitiveActionTitle: 'Sensitive action requested',
  sensitiveActionPrompt: 'Execute it?',
  actionSettle: 'Action settle (ms)',
  doubleTapInterval: 'Double tap interval (ms)',
  keyboardStep: 'Keyboard step (ms)',
  supportedActions: 'Supported actions',
  capabilities: [
    'Launch',
    'Tap',
    'Type',
    'Swipe',
    'Back',
    'Home',
    'Long press',
    'Double tap',
    'Wait',
    'Take over',
  ],
  androidScreenshot: 'Android screenshot',
  expandedAndroidScreenshot: 'Expanded screenshot for Android screenshot',
  screenshotInteractionLayer: 'Screenshot interaction layer',
  runGeneratedAction: 'Run generated action',
  clearGeneratedAction: 'Clear generated action',
  openScreenshotFor: (title: string) => `Open screenshot for ${title}`,
  screenshotDialogFor: (title: string) => `Screenshot for ${title}`,
  closeScreenshotPreview: 'Close screenshot preview',
  screenshotZoomControls: 'Screenshot zoom controls',
  zoomInScreenshot: 'Zoom in screenshot',
  zoomOutScreenshot: 'Zoom out screenshot',
  resetScreenshotZoom: 'Reset screenshot zoom',
  showPhoneFullscreen: 'Show phone fullscreen',
  exitPhoneFullscreen: 'Exit phone fullscreen',
  fullscreenPhonePreview: 'Fullscreen phone preview',
  noScreenshot: 'No screenshot',
  chat: 'Chat',
  conversation: 'Conversation',
  noMessages: 'No messages yet',
  chatMessage: 'Chat message',
  chatPlaceholder: 'Send a follow-up instruction...',
  taskTemplate: 'Task template',
  chooseTaskTemplate: 'Choose a template...',
  send: 'Send',
  newChat: 'New chat',
  typeMessageFirst: 'Type a message first.',
  agentRun: 'Agent run',
  executionMode: 'Execution mode',
  manualMode: 'Plan one step',
  autoMode: 'Auto run',
  planNextStep: 'Plan next step',
  runAgent: 'Run agent',
  running: 'Running...',
  runUnavailable: 'Connect a device, configure the model, and send or choose a task first.',
  waitForCurrentRun: 'Wait for the current run to finish.',
  maxSteps: 'Max steps',
  autoExecute: 'Auto execute',
  runOptions: 'Run options',
  plan: 'Plan',
  run: 'Run',
  stop: 'Stop',
  reset: 'Reset',
  export: 'Export',
  pendingAction: 'Pending action',
  step: 'Step',
  none: 'None',
  acknowledge: 'Acknowledge',
  finish: 'Finish',
  execute: 'Execute',
  user: 'User',
  assistant: 'Assistant',
  observation: 'Observation',
  runLog: 'Run Log',
  clear: 'Clear',
  noEvents: 'No events yet',
} as const
